import type { Metadata } from "next";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

import "./globals.css";
import Nawigacja from "./navBar";
import Stopka from "./footer";

export const metadata: Metadata = {
  title: "Zootopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        <Nawigacja />
        {children}
        <Stopka />
      </body>
    </html>
  );
}
